### ISSUE TITLE
Software cannot be opened because it needs to be updated

### ISSUE THREAD

**Issue by zuzaglog** [downloadsoundcloud/desktop#1]
Hello there,
I just downloaded the newest release of the Mac zip package. I received the following pop up:
"“downloadsound.cloud” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information. This item is on the disk image “downloadsound.cloud-0.0.14.dmg”. Safari downloaded this disk image today at 13:52 from github-releases.githubusercontent.com."

I am running macOS Big Sur version 11.3.1 on MacBook Pro 15-inch 2018 

I solved the issue by doing the "open anyway" but then I run into a Type Error 
<img width="253" alt="image" src="https://user-images.githubusercontent.com/55582803/119260631-ffdb7c80-bbd3-11eb-8ccc-a0f75fb18d3e.png">

any idea how to fix this?

**Comment by zuzaglog** [comment]
It worked after trying to log in 3 times... You can delete the issue.

**Comment by zackradisic** [comment]
@zuzaglog Thanks for letting me know about this issue! That's really odd, I'll look into it 👍
